name: flutter_templates
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  signals: ^6.0.2
  go_router: ^14.8.1
  flutter_smart_dialog: ^4.9.8+7
  dio: ^5.8.0+1
  logger: ^2.5.0
  meta: ^1.16.0
  rxdart: ^0.28.0
  fpdart: ^1.1.1
  easy_refresh: ^3.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icon_font_generator: ^4.0.0
  husky: ^0.1.7
  color_gen:
    path: ./color_gen

dependency_overrides:
  logger: ^2.5.0

flutter:
  uses-material-design: true

  # 需要图标的话把 svg 放到 icon 目录里面然后运行 dart run icon_font_generator:generator 就行了
  # fonts:
  #   - family: CustomIcon
  #     fonts:
  #       - asset: lib/icon/icon.otf
